### ISSUE TITLE
整理 API 需求 (1/2)

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#330]
#331 
整理出 API 編號、Method、參數以及回傳的 json 格式

- [x] [001](#001): ` /app` 區塊鏈、貨幣、黑名單數量 
- [x] [002](#002): `/app/chains` 區塊鏈的資料，包含 chainId、chainName、blocks、transactions 
- [x] [003](#003): `/app/chains/[chainId]` chainId、block list、transaction list 
- [x] [004](#004): `/app/chains/[chainId]/block/[blockId]` block detail、previousBlockId、nextBlockId 
- [x] [005](#005): `/app/chains/[chainId]/transaction/[transactionId]` transaction detail
- [x] [006](#006): `/app/chains/[chainId]/address/[addressId]` address detail、transaction history、block produced history
- [x] [007](#007): `/app/chains/[chainId]/address/[addressId]/reviews` review list、score
- [x] [008](#008): `/app/chains/[chainId]/address/[addressId]/red-flag` red flag list
- [x] [009](#009): `/app/chains/[chainId]/address/[addressId]/interaction` interaction list (include address & contract)

**Comment by Julian0701** [comment]
Home Page，顯示區塊鏈、貨幣、黑名單數量的資料
```ts
export interface IPromotion {
  chains: number | string;
  cryptoCurrencies: number | string;
  blackList: number | string;
}
```

**Comment by Julian0701** [comment]
All Chains，顯示各個區塊鏈的名稱，區塊數和交易量
```ts
[
    {
      "id": "eth",
      "name": "Ethereum",
      "icon": "/currencies/eth.svg",
      "blocks": 56789,
      "totalTransactions": 123456
    },
    {
      "id": "bit",
      "name": "Bitcoin",
      "icon": "/currencies/bit.svg",
      "blocks": 67890,
      "totalTransactions": 987654
    },
    {
      "id": "isun",
      "name": "iSunCloud",
      "icon": "/currencies/isun.svg",
      "blocks": 17313,
      "totalTransactions": 917361
    },
    {
      "id": "usdt",
      "name": "Tether",
      "icon": "/currencies/usdt.svg",
      "blocks": 34567,
      "totalTransactions": 567890
    },
    {
      "id": "bnb",
      "name": "Binance",
      "icon": "/currencies/bnb.svg",
      "blocks": 45678,
      "totalTransactions": 789012
    }
    // ... other chains
  ]
```

**Comment by Julian0701** [comment]
- take 1 hr, remain 4 hrs

**Comment by Julian0701** [comment]
- 編號: 003
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "blockId": "230021", 
  "chainId": "isun",
  "stability": "HIGH", //'MEDIUM' | 'HIGH' | 'LOW'
  "createdTimestamp": 1679978900,
  "managementTeam": ["Alice", "Bob", "Charlie"],
  "transactionCount": 25,
  "miner": "0x1234567890",
  "reward": 2.5, 
  "size": 3523 //bytes
}
```
- 所屬頁面: `/app/chains/[chainId]`

**Comment by Julian0701** [comment]
- 編號: 004
- Url: `/app/chains/[chainId]/block/[blockId]`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "id": "230021", 
  "chainId": "isun",
  "stability": "HIGH", //"MEDIUM" | "HIGH" | "LOW"
  "createdTimestamp": 1679978900,
  "managementTeam": ["Alice", "Bob", "Charlie"],
  "transactionCount": 25,
  "miner": "0x1234567890",
  "reward": 2.5, 
  "size": 3523 //bytes
  "previousBlockId": "230020",
  "nextBlockId": "230022"
}

**Comment by Julian0701** [comment]
- 編號: 005
- Url: `/app/chains/[chainId]/transaction/[transactionId]`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "id": "930071",
  "hash": "0xE47Dcf8aF9829AD3c4E31409eB6ECfecd046d1BD",
  "type": "NFT",
  "status": "PROCESSING",
  "chainId": "isun",
  "blockId": "230021",
  "createdTimestamp": 1688342795,
  "fromAddressId": "130008",
  "toAddressId": "310029",
  "evidenceId": "530029",
  "value": 0.01,
  "fee": 0.01,
  "flagging": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES"
}
```

**Comment by Julian0701** [comment]
- 編號: 006
- Url: `/app/chains/[chainId]/address/[addressId]`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "id": "110132",
  "type": "address",
  "addressHash": "0x2775D3190693fEc256d156f9f74Cd8843A79",
  "chainId": "btc",
  "createdTimestamp": 1680827461,
  "lastestActiveTime": 1682935384,
  "relatedAddressIds": ["110029", "112840", "114007"],
  "interactedAddressCount": 3,
  "interactedContactCount": 2,
  "transactionHistoryData": [
    {
      "id": "930154",
      "createdTimestamp": 1679978987,
      "type": "Crypto Currency",
      "status": "SUCCESS",
    },
    {
      "id": "930785",
      "createdTimestamp": 1687909392,
      "type": "Evidence",
      "status": "FAILED",
    },
  ],
  "blockProducedData": [
    {
      "id": "230976",
      "createdTimestamp": 1678940724,
      "stability": "MEDIUM",
    },
    {
      "id": "234680",
      "createdTimestamp": 1684176283,
      "stability": "LOW",
    },
  ],
  "flagging": [
    {
      "id": "71839",
      "chainId": "btc",
      "addressId": "110132",
      "addressHash": "0x2775D3190693fEc256d156f9f74Cd8843A79",
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_TRANSFER",
      "createdTimestamp": 1679148493,
      "interactedAddressIds": ["110029", "112840", "114007"],
      "totalAmount": 101,
      "transactionHistoryData": [
        {
          "id": "932840",
          "createdTimestamp": 1679986039,
          "type": "Crypto Currency",
          "status": "FAILED",
        },
      ],
    },
  ],
  "riskLevel": "MEDIUM_RISK",
  "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
}
```

**Comment by Julian0701** [comment]
- 編號: 007
- Url: `/app/chains/[chainId]/address/[addressId]/reviews`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "score": 2.8,
  "reviewData": [
    {
      "id": "T99283100001",
      "transactionId": "992831",
      "chainId": "eth",
      "createdTimestamp": 1675289690,
      "authorAddressId": "392801",
      "content": "This is a review",
      "stars": 3,
    },
    {
      "id": "T99283100002",
      "transactionId": "992831",
      "chainId": "eth",
      "createdTimestamp": 1675351393,
      "authorAddressId": "331824",
      "content": "This is a review",
      "stars": 2,
    },
    {
      "id": "T93823000002",
      "transactionId": "938230",
      "chainId": "eth",
      "createdTimestamp": 1679589352,
      "authorAddressId": "327923",
      "content": "This is a review",
      "stars": 5,
    },
    {
      "id": "T98139400002",
      "transactionId": "981394",
      "chainId": "eth",
      "createdTimestamp": 1684378204,
      "authorAddressId": "322372",
      "content": "This is a review",
      "stars": 1,
    },
  ],
}
```

**Comment by Julian0701** [comment]
- 編號: 008<a name='008'></a>
- Url: `/app/chains/[chainId]/address/[addressId]/red-flag`
- Method: GET
- Parameters: 
- 回傳格式:

```json
[
  {
    "id": "A1300200001",
    "chainId": "isun",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
    "createdTimestamp": 1679978900,
  },
  {
    "id": "A1300200002",
    "chainId": "isun",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES",
    "createdTimestamp": 1680183194,
  },
  {
    "id": "A1300200003",
    "chainId": "isun",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682194724,
  },
  {
    "id": "A1300200004",
    "chainId": "isun",
    "addressId": "130020",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682729103,
  },
]
```

**Comment by Julian0701** [comment]
- take 6 hrs
