### ISSUE TITLE
整理 API 需求 (2/2)

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#332]
#331 
整理出 API 編號、Method、參數以及回傳的 json 格式

- [x] [010](#010): `/app/chains/[chainId]/contract/[contractId]` contract detail、transaction history
- [x] [011](#011): ` /app/chains/[chainId]/evidence/[evidenceId]` evidence detail、transaction history
- [x] [012](#012): `/app/currencies` crypto currency list
- [x] [013](#013): `/app/currencies/[currencyId]` currency detail、top 100 holder list、transaction history
- [x] [014](#014): `/app/currencies/[currencyId]/red-flag` 
- [x] [015](#015): `/app/blacklist` black list
- [x] [016](#016): `/app/red-flag` red flag list
- [x] [017](#017): `/app/red-flag/[redFlagId]` red flag detail、transaction history
- [x] [018](#018): `/app/transaction-list` 填入一個 blockId 或兩個 addressId ，回傳 transaction list
- [x] [019](#019): `/app/searching-result` 填入 keyword ，回傳 (IBlock | IAddress | IContract | IEvidence | ITransaction | IRedFlag)[]

**Comment by Julian0701** [comment]
- 編號: 010<a name='010'></a>
- Url: `/app/chains/[chainId]/contract/[contractId]`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "id": "330029",
  "type": "contract",
  "contractAddress": "0xA9D1e08C7793af67e9d92fe308d5697FB81d3E43",
  "chainId": "isun",
  "creatorAddressId": "130008",
  "createdTimestamp": 1688341795,
  "sourceCode": "",
  "transactionData": [
    {
      "id": "930918",
      "createdTimestamp": 1689957331,
      "toAddressId": "329013",
      "status": "SUCCESS",
    },
    {
      "id": "932726",
      "createdTimestamp": 1692977381,
      "toAddressId": "339103",
      "status": "PENDING",
    },
  ],
  "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
}
```

**Comment by Julian0701** [comment]
- 編號: 011<a name='011'></a>
- Url: `/app/chains/[chainId]/evidence/[evidenceId]`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "id": "510071",
  "chainId": "btc",
  "evidenceAddess": "0x2326ce42a513a427a1ab5045a684e0a8ee8e96a13",
  "state": "Active",
  "creatorAddressId": "114007",
  "createdTimestamp": 1687103913,
  "content": "",
  "transactionData": [
    {
      "id": "918436",
      "createdTimestamp": 1682817342,
      "toAddressId": "313823",
      "status": "FAILED",
    },
    {
      "id": "913827",
      "createdTimestamp": 1684029313,
      "toAddressId": "309135",
      "status": "SUCCESS",
    },
  ],
}
```

- take 0.5 hr

**Comment by Julian0701** [comment]
- 編號: 012<a name='012'></a>
- Url: `/app/currencies`
- Method: GET
- Parameters: 
- 回傳格式:

```json
[
  {
    "currencyId": "btc",
    "currencyName": "Bitcoin",
    "rank": 1,
    "riskLevel": "HIGH_RISK",
  },
  {
    "currencyId": "eth",
    "currencyName": "Ethereum",
    "rank": 2,
    "riskLevel": "MEDIUM_RISK",
  },
  {
    "currencyId": "isun",
    "currencyName": "iSunCloud",
    "rank": 3,
    "riskLevel": "LOW_RISK",
  },
  {
    "currencyId": "usdt",
    "currencyName": "Tether",
    "rank": 4,
    "riskLevel": "MEDIUM_RISK",
  },
  {
    "currencyId": "bnb",
    "currencyName": "Binace Coin",
    "rank": 5,
    "riskLevel": "LOW_RISK",
  },
  // other currencies
]
```

- take 0.5 hr

**Comment by Julian0701** [comment]
- 編號: 013<a name='013'></a>
- Url: `/app/currencies/[currencyId]`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "currencyId": "btc",
  "currencyName": "Bitcoin",
  "rank": 1,
  "price": 27755.4,
  "volumeIn24h": 14867304472,
  "unit": "BTC",
  "totalAmount": 19388600,
  "holders": [
    {
      "addressId": "110029",
      "holdingAmount": 248597,
      "holdingPercentage": 1.28,
      "publicTag": ["PUBLIC_TAG.BINANCE_COLDWALLET"],
    },
    {
      "addressId": "110132",
      "holdingAmount": 178010,
      "holdingPercentage": 0.92,
      "publicTag": ["PUBLIC_TAG.BINANCE_COLDWALLET"],
    },
    {
      "addressId": "112840",
      "holdingAmount": 117351,
      "holdingPercentage": 0.61,
      "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    },
    {
      "addressId": "114007",
      "holdingAmount": 93109,
      "holdingPercentage": 0.48,
      "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    },
    {
      "addressId": "115588",
      "holdingAmount": 62352,
      "holdingPercentage": 0.32,
      "publicTag": ["PUBLIC_TAG.UNKNOWN_USER"],
    },
    // other holders
  ],
  "totalTransfers": 48010097,
  "flaggingCount": 24,
  "riskLevel": "HIGH_RISK",
  "transactionHistoryData": [
    {
      "id": "910154",
      "createdTimestamp": 1679987093,
      "type": "Crypto Currency",
      "status": "SUCCESS",
    },
    {
      "id": "910785",
      "createdTimestamp": 1689787324,
      "type": "Evidence",
      "status": "FAILED",
    },
    // ...other transaction history
  ],
}
```

**Comment by Julian0701** [comment]
- 編號: 014<a name='014'></a>
- Url: `/app/currencies/[currencyId]/red-flag`
- Method: GET
- Parameters: 
- 回傳格式:

```json
[
    {
      "id": "A1183720028",
      "chainId": "btc",
      "addressId": "118372",
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES",
      "createdTimestamp": 1679099781,
    },
    {
      "id": "A1132480029",
      "chainId": "btc",
      "addressId": "113248",
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
      "createdTimestamp": 1682172429,
    },
    {
      "id": "A1182740004",
      "chainId": "btc",
      "addressId": "118274",
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_BLACK_LIST",
      "createdTimestamp": 1689427103,
    },
    {
      "id": "A1192830192",
      "chainId": "btc",
      "addressId": "119283",
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MIXING_SERVICE",
      "createdTimestamp": 1689427103,
    }
   // ... other red flag
  ]
```

**Comment by Julian0701** [comment]
- 編號: 015<a name='015'></a>
- Url: `/app/blacklist`
- Method: GET
- Parameters: 
- 回傳格式:

```json
[
  {
    "id": "120008",
    "chainId": "eth",
    "lastestActiveTime": 1686710310,
    "flaggingRecords": ["RED_FLAG_DETAIL_PAGE.FLAG_TYPE_HIGH_RISK_LOCATION"],
    "publicTag": ["PUBLIC_TAG.HACKER"],
  },
  {
    "id": "143281",
    "chainId": "usdt",
    "lastestActiveTime": 1690283421,
    "flaggingRecords": [
      "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
      "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
    ],
    "publicTag": ["PUBLIC_TAG.HACKER"],
  },
  {
    "id": "117263",
    "chainId": "btc",
    "lastestActiveTime": 1682740134,
    "flaggingRecords": [
      "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_TRANSFER",
      "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES",
    ],
    "publicTag": ["PUBLIC_TAG.HACKER"],
  },
  // ...other blacklisted addresses
]
```

**Comment by Julian0701** [comment]
- 編號: 016<a name='016'></a>
- Url: `/app/red-flag`
- Method: GET
- Parameters: 
- 回傳格式:

```json
[
  {
    "id": "A1223724980",
    "chainId": "eth",
    "addressId": "122372",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_TRANSFER",
    "createdTimestamp": 1677769870,
  },
  {
    "id": "A1132480029",
    "chainId": "btc",
    "addressId": "113248",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_WITHDRAW",
    "createdTimestamp": 1682172429,
  },
  {
    "id": "A1468697785",
    "chainId": "usdt",
    "addressId": "146869",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_GAMBLING_SITE",
    "createdTimestamp": 1686548904,
  },
  {
    "id": "A1378976701",
    "chainId": "isun",
    "addressId": "137897",
    "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_LARGE_DEPOSIT",
    "createdTimestamp": 1690657412,
  },
  // ... other red flag
]
```

**Comment by Julian0701** [comment]
- 編號: 017<a name='017'></a>
- Url: `/app/red-flag`
- Method: GET
- Parameters: 
- 回傳格式:

```json
{
  "id": "1400520038",
  "chainId": "usdt",
  "addressId": "140052",
  "addressHash": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984",
  "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_WITHDRAW",
  "createdTimestamp": 1686579200,
  "interactedAddressIds": ["140197", "141253", "144282", "149371"],
  "totalAmount": 100,
  "transactionData": [
    {
      "id": "943029",
      "createdTimestamp": 1686579229,
      "toAddressId": "123452",
      "status": "SUCCESS",
    },
    {
      "id": "944291",
      "createdTimestamp": 1687860718,
      "toAddressId": "181716",
      "status": "PENDING",
    },
    //...
  ],
}
```

**Comment by Julian0701** [comment]
- 編號: 018<a name='018'></a>
- Url: `/app/transaction-list`
- Method: GET
- Parameters: 

| name | type | description |
| --- | --- | --- |
| blockId | string | 區塊 Id |
| addressId | string | 地址 Id ，須帶兩個 |
- 回傳格式:

```json
[
  {
    "id": "916841",
    "chainId": "btc",
    "createdTimestamp": 1678057313,
    "type": "Crypto Currency",
    "status": "SUCCESS",
  },
  {
    "id": "910237",
    "chainId": "btc",
    "createdTimestamp": 1681731057,
    "type": "Evidence",
    "status": "SUCCESS",
  },
  {
    "id": "910237",
    "chainId": "btc",
    "createdTimestamp": 1683905718,
    "type": "Crypto Currency",
    "status": "SUCCESS",
  },
  {
    "id": "919472",
    "chainId": "btc",
    "createdTimestamp": 1689732890,
    "type": "Evidence",
    "status": "FAILED",
  },
  {
    "id": "911837",
    "chainId": "btc",
    "createdTimestamp": 1690209183,
    "type": "Crypto Currency",
    "status": "PENDING",
  }
  // ...other transactions
]
```

**Comment by Julian0701** [comment]
- 編號: 019<a name='019'></a>
- Url: `/app/searching-result`
- Method: GET
- Parameters: 

| name | type | description |
| --- | --- | --- |
| search | string | 關鍵字 |
- 回傳格式:

```json
[
  {
    "type": "BLOCK",
    "data": {
      "id": "210018",
      "chainId": "btc",
      "createdTimestamp": 1665798400,
      "stability": "MEDIUM",
    },
  },
  {
    "type": "ADDRESS",
    "data": {
      "id": "148208",
      "chainId": "usdt",
      "createdTimestamp": 1682940241,
      "addressHash": "0x278432201",
      "flaggingCount": 10,
      "riskLevel": "MEDIUM_RISK",
    },
  },
  {
    "type": "CONTRACT",
    "data": {
      "id": "314839",
      "chainId": "btc",
      "createdTimestamp": 1681918401,
      "contractAddress": "0x444357813",
    },
  },
  {
    "type": "EVIDENCE",
    "data": {
      "id": "528401",
      "chainId": "eth",
      "createdTimestamp": 1680421348,
      "evidenceAddess": "0x898765432",
    },
  },
  {
    "type": "TRANSACTION",
    "data": {
      "id": "924044",
      "chainId": "eth",
      "createdTimestamp": 1684482143,
      "hash": "0x213456789",
    },
  },
  {
    "type": "BLACKLIST",
    "data": {
      "id": "142523",
      "chainId": "usdt",
      "createdTimestamp": 1684801889,
      "addressHash": "0x270183713",
      "publicTag": ["PUBLIC_TAG.HACKER"],
    },
  },
  {
    "type": "RED_FLAG",
    "data": {
      "id": "1138290086",
      "chainId": "btc",
      "createdTimestamp": 1689244021,
      "addressHash": "0x383488493",
      "redFlagType": "RED_FLAG_DETAIL_PAGE.FLAG_TYPE_MULTIPLE_RECEIVES",
    },
  },
// ... other result
]
```
