### ISSUE TITLE
設定 Prisma schema 

### ISSUE THREAD

**Issue by Julian0701** [CAFECA-IO/BAIFA#503]
根據 DB 設定 Prisma schema ，並移除 pg

**Comment by Julian0701** [comment]
需要複查以下 API ，在需要的地方補上 ToDo 或註解
 - [ ] 004 - Get data from chains [#431](https://github.com/CAFECA-IO/BAIFA/issues/431)
  - [ ] 005 - Get all data from a chain [#432](https://github.com/CAFECA-IO/BAIFA/issues/432)
  - [ ] 006 - Select period for blocks [#433](https://github.com/CAFECA-IO/BAIFA/issues/433)
  - [ ] 007 - Get a block data from a chain [#434](https://github.com/CAFECA-IO/BAIFA/issues/434)
  - [ ] 008 - Transaction List form a block [#435](https://github.com/CAFECA-IO/BAIFA/issues/435) 
  - [ ] 009 - Select period for transactions / Transaction History from Addresses [#436](https://github.com/CAFECA-IO/BAIFA/issues/436) 
  - [ ] 010 - Get a transaction data from a chain [#437](https://github.com/CAFECA-IO/BAIFA/issues/437)
  - [ ] 016 - Get evidence data from a chain [#443](https://github.com/CAFECA-IO/BAIFA/issues/443)

**Comment by Julian0701** [comment]
- take 2 hrs
