### ISSUE TITLE
貨幣詳細 `/app/currencies/[currencyId]`

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#593]
# Currency Detail page  - frontend adjustment 

後端 API 已串上資料庫
若資料庫尚未有資料則需要先在資料庫內新增一筆假資料作為測試

確認並調整(評估時數不足則另外再開單):
- [x] 畫面部分資料是否有正確顯示
- [x] 渲染過程不可以跳出 N/A
- [x] 處理 Error handler → data not found 畫面
- [x] Loading time > 3 secs 需要改善

新增:
- [x] Total Amount incorrect
- [x] Search result incorrect
- [x] fix Time column
- [x] fix Status column → 目前是寫假的資料 `Success`，且不確定此欄位是否會刪除
- [x] #711
- [x] #712
- [x] #718 
- [x] #719
- [x] #721

---

相關資訊:
- 目前畫面: https://baifa.io/en/app/currencies/0xc035f74413c02433cabef9fe072d35f8f2f1cac6?page=1
- API : [018](https://github.com/CAFECA-IO/BAIFA/wiki/API-v1.1.0#018---get-data-from-a-currency)
- file relative path : `src/pages/app/currencies/[currencyId]/index.tsx`
- Schema files:
  - [codes](https://github.com/CAFECA-IO/Documents/blob/main/BFA/db_schema/codes.md)
  - [currencies](https://github.com/CAFECA-IO/Documents/blob/main/BFA/db_schema/currencies.md)
  - [token_transfers](https://github.com/CAFECA-IO/Documents/blob/main/BFA/db_schema/token_transfers.md)
  - [token_balances](https://github.com/CAFECA-IO/Documents/blob/main/BFA/db_schema/token_balances.md)

**Comment by godmmt** [comment]
# 新增子任務

![截圖 2024-02-07 下午4 10 41](https://github.com/CAFECA-IO/BAIFA/assets/105651918/c5a11eca-a562-435a-8eaa-d1d6db6a3087)

- [ ] Total Amount incorrect

![截圖 2024-02-07 下午4 12 20](https://github.com/CAFECA-IO/BAIFA/assets/105651918/02b67606-791e-44fb-b3dd-9c4800c766ca)

- [ ] Search result incorrect
- [ ] fix Time column
- [ ] fix Status column

**Comment by godmmt** [comment]
# Todo - 2024/02/16

![截圖 2024-02-16 上午10 51 13](https://github.com/CAFECA-IO/BAIFA/assets/105651918/9114d0a0-64a4-4a56-b98e-cd943620720a)

**Comment by godmmt** [comment]
# Todo - 2024/02/16

![截圖2024-02-16上午110916](https://github.com/CAFECA-IO/BAIFA/assets/105651918/7a432cda-055b-4164-970c-2f4757734676)

正確資料為
```json
[
  {
    "id": 24,
    "from_address": "0x048adee1b0e93b30f9f7b71f18b963ca9ba5de3b",
    "to_address": "0x5df5a902b83ce78f493dfb3e62afbd08c34ce9b6",
    "value": "10000000000000000000",
    "chain_id": 8017,
    "currency_id": "0xc035f74413c02433cabef9fe072d35f8f2f1cac6",
    "transaction_hash": "0xc326e3a067fa3443fcf0f5e12e42a0be7cac1ca52770cc225e5b22e49cce937d",
    "index": 1,
    "created_timestamp": 1707304079
  },
  {
    "id": 25,
    "from_address": "0x048adee1b0e93b30f9f7b71f18b963ca9ba5de3b",
    "to_address": "0x5df5a902b83ce78f493dfb3e62afbd08c34ce9b6",
    "value": "5000000000000000000",
    "chain_id": 8017,
    "currency_id": "0xc035f74413c02433cabef9fe072d35f8f2f1cac6",
    "transaction_hash": "0xa277b3c90d9886b869ee73211d81a04e70f0a72f08c83da2a2cd0cde01c99d42",
    "index": 1,
    "created_timestamp": 1707304622
  },
  {
    "id": 26,
    "from_address": "0x048adee1b0e93b30f9f7b71f18b963ca9ba5de3b",
    "to_address": "0x5df5a902b83ce78f493dfb3e62afbd08c34ce9b6",
    "value": "15000000000000000000",
    "chain_id": 8017,
    "currency_id": "0xc035f74413c02433cabef9fe072d35f8f2f1cac6",
    "transaction_hash": "0x00677112f7893adee014b73d9af47d48d4235e44a4e1fc04a1ccd54f5f6ffac6",
    "index": 1,
    "created_timestamp": 1707306192
  }
]
```

**Comment by godmmt** [comment]
currencyData?.total_amount 是一個字串，可能大於或小於 18 位數

最後顯示 total_amount，其格式要是：小數點後有18位數的字串、小數點前每三位數補一個逗號

**Comment by godmmt** [comment]
# interface update

**Comment by godmmt** [comment]
# Note

1. BigInt 計算後也不要轉 Number，就算相除也可能還是 BigInt，不要任意轉數字。

**Comment by godmmt** [comment]
# Relative Issues

- #710
- #711
- #712
- #718
- #719
- #721
- #727
- #790
- #852
- #877
- #883
- #899
- #919
- #953
- #959
- #968
- #1004
- #1036
